version: '3.8'

services:
  db:
    image: postgres:13
    container_name: pg_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admon
      POSTGRES_DB: backend
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data  # Persistencia personalizada
    networks:
      - mynetwork
  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    networks:
      - mynetwork
    volumes:
      - .:/app



networks:
  mynetwork:

